name: admet-agent
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit
  - pip
  - pip:
      - streamlit
      - python-dotenv
      - langchain-groq
      - langchain-core
      - faiss-cpu
      - sentence-transformers
      - numpy
      - pandas
      - beautifulsoup4
      - requests
